# Generated by Django 5.1.3 on 2024-11-14 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0005_vectordb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vectordb',
            name='vector_db_path',
            field=models.CharField(editable=False, max_length=255),
        ),
    ]
